name: Rebuild Site on Release

on:
  release:
    type: published

jobs:
  rebuild:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/github-script@0.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.repos.requestPageBuild(...context.repo)
